// Generated from successfully downloaded original Wiki files.
const localAssets={
  "Castle": "assets/cards/Castle.png",
  "Archer": "assets/cards/Archer.png",
  "Paladin": "assets/cards/Paladin.png",
  "Soldier": "assets/cards/Soldier.png",
  "Scout Tower": "assets/cards/Scout_Tower.png",
  "Blacksmith": "assets/cards/Blacksmith.png",
  "Farm": "assets/cards/Farm.png",
  "Steel Coat": "assets/cards/Steel_Coat.png",
  "Wildcard": "assets/cards/Wildcard.png",
  "Pagoda": "assets/cards/Pagoda.png",
  "Bomber": "assets/cards/Bomber.png",
  "Imp": "assets/cards/Imp.png",
  "Mangler": "assets/cards/Mangler.png",
  "Cemetery": "assets/cards/Cemetery.png",
  "Demon's Altar": "assets/cards/Demon's_Altar.png",
  "Carnage": "assets/cards/Carnage.png",
  "Oblation": "assets/cards/Oblation.jpg",
  "Sacrifice": "assets/cards/Sacrifice.png",
  "Palace": "assets/cards/Palace.png",
  "Thief": "assets/cards/Thief.png",
  "Mercenary": "assets/cards/Mercenary.png",
  "Dispenser": "assets/cards/Dispenser.png",
  "Beacon": "assets/cards/Beacon.png",
  "Vault": "assets/cards/Vault.png",
  "Midas Touch": "assets/cards/Midas_Touch.png",
  "Over-invest": "assets/cards/Over-invest.png",
  "Mortage": "assets/cards/Mortage.png",
  "Treant": "assets/cards/Treant.png",
  "Boar": "assets/cards/Boar.png",
  "Elf": "assets/cards/Elf.png",
  "Orchard": "assets/cards/Orchard.png",
  "Forest": "assets/cards/Forest.png",
  "Mycelium": "assets/cards/Mycelium.png",
  "Poison Vial": "assets/cards/Poison_Vial.png",
  "Clone": "assets/cards/Clone.png",
  "Procreate": "assets/cards/Procreate.png",
  "Warlord": "assets/cards/Warlord.png",
  "Mob": "assets/cards/Mob.png",
  "Raptor": "assets/cards/Raptor.png",
  "Dragon's Den": "assets/cards/Dragon's_Den.png",
  "Camp": "assets/cards/Camp.png",
  "Frost": "assets/cards/Frost.png",
  "Migration": "assets/cards/Migration.png",
  "Shields": "assets/cards/Shields.png",
  "Swords": "assets/cards/Swords.png",
  "Mothership": "assets/cards/Mothership.png",
  "Defender": "assets/cards/Defender.png",
  "Executioner": "assets/cards/Executioner.png",
  "Lab Rat": "assets/cards/Lab_Rat.png",
  "Converter": "assets/cards/Converter.png",
  "Concabulator": "assets/cards/Concabulator.png",
  "Recycler": "assets/cards/Recycler.jpg",
  "Reinforce": "assets/cards/Reinforce.png",
  "Overhaul": "assets/cards/Overhaul.png",
  "Citadel": "assets/cards/Citadel.png",
  "Shaman": "assets/cards/Shaman.png",
  "Warlock": "assets/cards/Warlock.png",
  "Wizard": "assets/cards/Wizard.png",
  "Spire": "assets/cards/Spire.png",
  "Library": "assets/cards/Library.png",
  "Combustion": "assets/cards/Combustion.png",
  "Static": "assets/cards/Static.png",
  "Offering": "assets/cards/Offering.png",
  "Stronghold": "assets/cards/Stronghold.png",
  "Ballista": "assets/cards/Ballista.png",
  "Trapper": "assets/cards/Trapper.png",
  "Flamethrower": "assets/cards/Flamethrower.png",
  "Trebuchet": "assets/cards/Trebuchet.png",
  "Cauldron": "assets/cards/Cauldron.png",
  "Quarry": "assets/cards/Quarry.png",
  "Wallmaker": "assets/cards/Wallmaker.png",
  "Earthworks": "assets/cards/Earthworks.png",
  "Bastion": "assets/cards/Bastion.png",
  "Warper": "assets/cards/Warper.png",
  "Orbiter": "assets/cards/Orbiter.png",
  "Portal": "assets/cards/Portal.png",
  "Hourglass": "assets/cards/Hourglass.png",
  "Amplifier": "assets/cards/Amplifier.png",
  "Rewind": "assets/cards/Rewind.png",
  "Adrenaline": "assets/cards/Adrenaline.png",
  "Regression": "assets/cards/Regression.png",
  "TempNull": "assets/cards/TempNull.png",
  "Echoform": "assets/cards/Echoform.png",
  "Gigantify": "assets/cards/Gigantify.png",
  "Haste": "assets/cards/Haste.png",
  "Ogre": "assets/cards/Ogre.png",
  "Golem": "assets/cards/Golem.png",
  "Patronage": "assets/cards/Patronage.png",
  "Razing": "assets/cards/Razing.png",
  "Scapegoat": "assets/cards/Scapegoat.png",
  "Shrine": "assets/cards/Shrine.png",
  "Gacha": "assets/cards/Gacha.png",
  "Slime": "assets/cards/Slime.png",
  "Temple": "assets/cards/Temple.png",
  "Unify": "assets/cards/Unify.png",
  "X-Ray": "assets/cards/X-Ray.png",
  "Osmosis": "assets/cards/Osmosis.png",
  "Randomify": "assets/cards/Randomify.png",
  "Replicator": "assets/cards/Replicator.png",
  "Balance": "assets/cards/Balance.png",
  "King of Nothing": "assets/kings/King_of_Nothing.png",
  "King of Spells": "assets/kings/King_of_Spells.png",
  "King of Greed": "assets/kings/King_of_Greed.png",
  "King of Blood": "assets/kings/King_of_Blood.png",
  "King of Nature": "assets/kings/King_of_Nature.png",
  "King of Nomads": "assets/kings/King_of_Nomads.png",
  "King of Stone": "assets/kings/King_of_Stone.png",
  "King of Progress": "assets/kings/King_of_Progress.png",
  "King of Time": "assets/kings/King_of_Time.png",
  "Mortgage": "assets/cards/Mortage.png",
  "Over-Invest": "assets/cards/Over-invest.png"
};
