const kings=[
{name:'Rei do Nada',en:'King of Nothing',tag:'defesa',color:'#d6c18c',build:'Paladino + Ferreiro + Fazenda + Proteção de Aço',desc:'Transforme uma unidade defensiva em um exército com vida e dano crescentes.',cards:[['Paladino','Paladin','Tropa corpo a corpo resistente. Bônus de dano também aumentam sua vida.'],['Ferreiro','Blacksmith','Aumenta anualmente o dano das tropas e construções adjacentes.'],['Fazenda','Farm','Acrescenta unidades a uma tropa adjacente a cada ano.'],['Proteção de Aço','Steel Coat','Impede o primeiro golpe que a unidade sofreria em cada combate.']],why:'O Ferreiro fortalece o ataque do Paladino e, pela habilidade especial dele, também sua vida. A Fazenda acrescenta Paladinos; a Proteção de Aço melhora a sobrevivência.',place:'Coloque Paladinos junto de Ferreiros e Fazendas; mantenha o foco nos bônus dessa tropa.',result:'Vida e dano crescentes',url:'https://9kings.wiki.gg/wiki/King_of_Nothing'},
{name:'Rei dos Feitiços',en:'King of Spells',tag:'dano',color:'#b898e7',build:'Mago + 4 Bibliotecas + Combustão + Estática',desc:'Concentre efeitos mágicos em uma única tropa de alto dano.',cards:[['Mago','Wizard','Atacante à distância com golpes potentes e lentos.'],['Biblioteca','Library','Tem chance anual de duplicar uma carga de encantamento de tropa adjacente.'],['Combustão','Combustion','Provoca dano em área quando a unidade elimina um inimigo.'],['Estática','Static','Adiciona raios em cadeia aos ataques; cargas aumentam seus efeitos.'],['Adrenalina (opcional)','Adrenaline','Aumenta gradualmente a velocidade de ataque durante a batalha.']],why:'Quatro Bibliotecas dão oportunidades de acumular encantamentos no Mago. Estática distribui dano por vários alvos e Combustão aproveita as eliminações.',place:'Use o Mago no centro e Bibliotecas acima, abaixo, à esquerda e à direita.',result:'Encantamentos acumulados',url:'https://9kings.wiki.gg/wiki/King_of_Spells'},
{name:'Rei da Ganância',en:'King of Greed',tag:'escala',color:'#e5bf57',build:'Dispensadores + Cofres + Hipoteca',desc:'Converta a produção de ouro em poder de ataque.',cards:[['Dispensador','Dispenser','Torre que acelera sua cadência ao ganhar ouro.'],['Cofre','Vault','Gera ouro ao fim de cada ano.'],['Hipoteca','Mortgage','Destrói um terreno para receber ouro conforme o nível da carta.'],['Superinvestimento (opcional)','Over-Invest','Consome ouro para aumentar atributos de uma tropa ou torre.']],why:'Cofres garantem entrada recorrente de ouro. Esse ganho fortalece os Dispensadores; Hipoteca acelera o processo quando há um terreno dispensável.',place:'Espalhe Cofres em áreas seguras e construa vários Dispensadores para concentrar fogo.',result:'Alta velocidade de ataque',url:'https://9kings.wiki.gg/wiki/King_of_Greed'},
{name:'Rei do Sangue',en:'King of Blood',tag:'dano',color:'#e66b72',build:'Bombardeiros + Raptores + Cemitério',desc:'Explosões rápidas com invocações que continuam pressionando o inimigo.',cards:[['Bombardeiro','Bomber','Corre até o inimigo e explode, causando dano em área.'],['Raptor','Raptor','Montaria para tropas próximas, ajudando no avanço e somando atributos.'],['Cemitério','Cemetery','Invoca diabretes quando tropas aliadas adjacentes morrem.'],['Pagode','Pagoda','Base do rei que invoca diabretes.'],['Fogos de Artifício (opcional)','Fireworks','Decreto que amplia a área das explosões dos Bombardeiros.']],why:'Raptores permitem que os Bombardeiros alcancem os alvos. A explosão abre espaço; o Cemitério transforma mortes aliadas em novas invocações.',place:'Mantenha Bombardeiros próximos dos Raptores e o Cemitério perto da zona de baixas.',result:'Explosões e substituição de tropas',url:'https://9kings.wiki.gg/wiki/King_of_Blood'},
{name:'Rei da Natureza',en:'King of Nature',tag:'escala',color:'#74c78a',build:'Javali + 3 Florestas + Elfos ou Paladinos',desc:'Aumente a vida de uma montaria para potencializar o cavaleiro.',cards:[['Javali','Boar','Montaria que concede bônus de atributos à tropa montada com base em sua própria vida.'],['Floresta','Forest','Aumenta anualmente a vida de tropas adjacentes.'],['Elfo','Elf','Atacante à distância que prioriza inimigos distantes.'],['Paladino (alternativa)','Paladin','Tropa resistente que aproveita bônus de dano e vida.'],['Procriar (opcional)','Procreate','Acrescenta unidades à tropa escolhida.']],why:'As Florestas fortalecem o Javali, aumentando o benefício que ele transmite à unidade que o monta.',place:'Cerque o Javali com Florestas e deixe uma tropa atacante adjacente para aproveitar a montaria.',result:'Atributos multiplicados',url:'https://9kings.wiki.gg/wiki/King_of_Nature'},
{name:'Rei da Pedra',en:'King of Stone',tag:'defesa',color:'#bbc0c4',build:'Muralha + Regressão + Torres',desc:'Uma Muralha que recebe melhorias repetidas segura inimigos enquanto as torres atacam.',cards:[['Construtor de Muralhas','Wallmaker','Cria estruturas defensivas que dificultam o avanço inimigo.'],['Muralha','Wall','Bloqueia inimigos e absorve ataques, com vida ampliada pelas evoluções.'],['Regressão','Regression','Reduz o nível da carta preservando atributos adquiridos.'],['Trabuco','Trebuchet','Torre de projéteis cuja quantidade cresce com as construções.'],['Pedreira (opcional)','Quarry','Melhora progressivamente o dano de torres e base.']],why:'Você evolui a Muralha, usa Regressão para reduzir o nível sem perder os atributos e a evolui outra vez. O ciclo acumula vida, enquanto as torres fazem o dano.',place:'Concentre evoluções em uma Muralha principal e posicione torres para protegê-la.',result:'Muralha com vida extrema',url:'https://9kings.wiki.gg/wiki/King_of_Stone',cycle:true},
{name:'Rei do Progresso',en:'King of Progress',tag:'escala',color:'#89d9ce',build:'Ratos de Laboratório + Cientista + Reformulação',desc:'Faça suas unidades crescerem além dos níveis convencionais.',cards:[['Ratos de Laboratório','Lab Rat','Sobem de nível quando terrenos adjacentes evoluem; podem exceder o nível habitual.'],['Cientista','Scientific','Vantagem permanente que melhora os níveis iniciais dos Ratos.'],['Reformulação','Overhaul','Destrói um terreno e concede níveis a outros terrenos.'],['Reforço (opcional)','Reinforce','Encantamento que aumenta o dano quando um terreno evolui.']],why:'Ratos vizinhos aproveitam evoluções próximas. Reformulação ajuda a gerar novos níveis e faz o conjunto crescer ao longo dos anos.',place:'Agrupe Ratos em terrenos adjacentes e concentre melhorias na região.',result:'Níveis elevados',url:'https://9kings.wiki.gg/wiki/King_of_Progress'},
{name:'Rei dos Nômades',en:'King of Nomads',tag:'escala',color:'#dfa77b',build:'Senhor da Guerra + 4 Acampamentos + Migração',desc:'Use movimento e construções para acumular bônus.',cards:[['Senhor da Guerra','Warlord','Base/tropa que fortalece unidades aliadas com base em seus atributos.'],['Acampamento','Camp','Concede bônus a terrenos próximos quando uma carta é colocada em terreno vazio.'],['Migração','Migration','Move uma carta para terreno vizinho vazio e aumenta seus atributos.'],['Espadas (opcional)','Swords','Adiciona dano à unidade selecionada.'],['Escudos (opcional)','Shields','Adiciona vida à unidade selecionada.']],why:'A Migração reforça a unidade e cria oportunidades para ativar efeitos dos Acampamentos. O Senhor da Guerra usa seus atributos para ajudar o exército.',place:'Tente cercar o Senhor da Guerra com Acampamentos e deixe espaços livres para movimentar.',result:'Bônus permanentes',url:'https://9kings.wiki.gg/wiki/King_of_Nomads'},
{name:'Rei do Tempo',en:'King of Time',tag:'escala',color:'#86b4e9',build:'Portal + Bênçãos + Sagrado + Amplificador',desc:'Repita eventos e aproveite multiplicadores ao longo dos anos.',cards:[['Portal','Portal','Em determinado nível, faz retornar anos mantendo progresso obtido.'],['Bênção de Vida','Peacetime','Evento que aumenta significativamente a vida de terrenos escolhidos.'],['Bênção de População','Baby Boom','Evento que aumenta o número de unidades de tropas escolhidas.'],['Sagrado','Holy','Vantagem permanente que aumenta o efeito das bênçãos.'],['Amplificador','Amplifier','Recebe bônus de atributos e os transmite para terrenos adjacentes.'],['Regressão (opcional)','Regression','Permite reduzir níveis sem apagar atributos adquiridos.']],why:'O Portal possibilita revisitar eventos vantajosos mantendo melhorias anteriores; Sagrado aumenta as bênçãos. Amplificador transmite bônus de atributos, mas não copia automaticamente eventos.',place:'Prepare seus terrenos para bênçãos e programe a evolução do Portal para repetir anos favoráveis.',result:'Bênçãos repetidas',url:'https://9kings.wiki.gg/wiki/King_of_Time'}
];

const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Caminhos de arquivo seguem a estrutura de imagens da wiki.gg. Alguns nomes podem variar.
// Imagens oficiais da wiki.gg usam frequentemente "<Carta> - <Rei>.png".
const cardOwners={
  'Paladin':'King of Nothing','Blacksmith':'King of Nothing','Farm':'King of Nothing','Steel Coat':'King of Nothing',
  'Wizard':'King of Spells','Library':'King of Spells','Combustion':'King of Spells','Static':'King of Spells','Adrenaline':'King of Time',
  'Dispenser':'King of Greed','Vault':'King of Greed','Mortgage':'King of Greed','Over-Invest':'King of Greed',
  'Bomber':'King of Blood','Raptor':'King of Blood','Cemetery':'King of Blood','Pagoda':'King of Blood','Fireworks':'King of Blood',
  'Boar':'King of Nature','Forest':'King of Nature','Elf':'King of Nature','Procreate':'King of Nature',
  'Wallmaker':'King of Stone','Wall':'King of Stone','Trebuchet':'King of Stone','Quarry':'King of Stone',
  'Lab Rat':'King of Progress','Overhaul':'King of Progress','Reinforce':'King of Progress',
  'Warlord':'King of Nomads','Camp':'King of Nomads','Migration':'King of Nomads','Swords':'King of Nomads','Shields':'King of Nomads',
  'Amplifier':'King of Time','Portal':'King of Time','Peacetime':'King of Time','Baby Boom':'King of Time','Holy':'King of Time',
  'Regression':'King of Stone'
};
// Links no formato de miniaturas da Wiki (images/thumb), sem arquivos originais em /images/<arquivo>.png.
const confirmedImages={
  'Paladin':'https://9kings.wiki.gg/images/thumb/Paladin_-_King_of_Nothing.png/600px-Paladin_-_King_of_Nothing.png?deff41'
};
const imageCandidates=name=>{
  const base=name.trim().replaceAll(' ','_');
  const owner=(cardOwners[name]||'').replaceAll(' ','_');
  const fileNames=[owner?`${base}_-_${owner}.png`:null,`${base}.png`,`${base}_card.png`].filter(Boolean);
  const thumbnails=fileNames.map(file=>`https://9kings.wiki.gg/images/thumb/${encodeURIComponent(file)}/600px-${encodeURIComponent(file)}`);
  return [...new Set([confirmedImages[name],...thumbnails].filter(Boolean))];
};
const pageOf=name=>'https://9kings.wiki.gg/wiki/'+encodeURIComponent(name.replaceAll(' ','_'));
const fallback=(name)=>'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="160" height="220" viewBox="0 0 160 220"><rect width="160" height="220" rx="14" fill="#e9edf2"/><rect x="8" y="8" width="144" height="204" rx="11" fill="#f8fafc" stroke="#b8c3d2" stroke-width="2"/><text x="80" y="88" font-size="35" text-anchor="middle" fill="#607895">♜</text><text x="80" y="118" text-anchor="middle" fill="#43546c" font-size="11" font-family="Arial">Imagem não disponível</text><text x="80" y="138" text-anchor="middle" fill="#718198" font-size="10" font-family="Arial">Abra na Wiki</text></svg>`);
const typeNames={defesa:'Defesa',dano:'Dano',escala:'Escalabilidade'};
function cardHtml(c,k,n,i){const [pt,en,desc]=c;const imgs=imageCandidates(en);const src=imgs[0];const page=pageOf(en);return `<div class="card"><button class="art-button" type="button" data-img="${esc(src)}" data-page="${esc(page)}" data-title="${esc(pt)}" aria-label="Ampliar carta ${esc(pt)}"><img loading="lazy" src="${esc(src)}" data-images="${esc(imgs.join('|'))}" data-fallback="${esc(fallback(en))}" alt="Carta ${esc(pt)} de Nine Kings"></button><div class="card-copy"><strong>${esc(pt)}</strong><small>${esc(en)}</small><p>${esc(desc)}</p><a href="${esc(page)}" target="_blank" rel="noopener noreferrer">Ver carta na Wiki ↗</a></div></div>`}
function render(){const q=$('search').value.toLocaleLowerCase('pt-BR').trim(),filter=$('filter').value;const visible=kings.filter(k=>(filter==='all'||filter===k.tag)&&[k.name,k.en,k.build,k.desc,k.why,k.place,...k.cards.flat()].join(' ').toLocaleLowerCase('pt-BR').includes(q));$('navigation').innerHTML=kings.map((k,i)=>`<a href="#rei-${i+1}">${esc(k.name)}</a>`).join('');$('builds').innerHTML=visible.map(k=>{const n=kings.indexOf(k)+1;return `<article class="king" id="rei-${n}"><div class="king-heading"><div><div class="king-no">REI ${String(n).padStart(2,'0')}</div><h2>${esc(k.name)}</h2></div><span class="category">${typeNames[k.tag]}</span></div><p class="build-label">${esc(k.build)}</p><p class="description">${esc(k.desc)}</p><p class="source"><a target="_blank" rel="noopener noreferrer" href="${esc(k.url)}">Ver página deste rei ↗</a></p><h3>O que cada carta faz</h3><div class="cards">${k.cards.map((c,i)=>cardHtml(c,k,n,i)).join('')}</div><h3>Por que essa combinação funciona?</h3><div class="combo"><p>${esc(k.why)}</p>${k.cycle?'<div class="cycle"><span>1. Evoluir Muralha</span><i>→</i><span>2. Regressão</span><i>→</i><span>3. Evoluir de novo</span><i>↻</i></div>':''}</div><p class="placement"><b>Como montar:</b> ${esc(k.place)}</p></article>`}).join('')||'<div class="none">Nenhuma build encontrada para sua pesquisa.</div>';$('summary').innerHTML=visible.map(k=>`<tr><td>${esc(k.name)}</td><td>${esc(k.build)}</td><td>${esc(k.result)}</td></tr>`).join('');document.querySelectorAll('.art-button img').forEach(img=>img.addEventListener('error',()=>{const urls=img.dataset.images.split('|');const index=Number(img.dataset.attempt||0)+1;img.dataset.attempt=String(index);if(index<urls.length){img.src=urls[index]}else{img.dataset.failed='1';img.src=img.dataset.fallback}}))}
$('search').addEventListener('input',render);$('filter').addEventListener('change',render);
$('builds').addEventListener('click',e=>{const btn=e.target.closest('.art-button');if(!btn)return;const img=btn.querySelector('img');$('preview-title').textContent=btn.dataset.title;$('preview-img').src=img.src;$('preview-img').alt=btn.dataset.title;$('preview-wiki').href=btn.dataset.page;$('preview-direct').href=img.dataset.failed?btn.dataset.page:img.src;$('preview').showModal()});
$('close-preview').addEventListener('click',()=>$('preview').close());$('preview').addEventListener('click',e=>{if(e.target===$('preview'))$('preview').close()});
$('theme').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('theme').textContent=dark?'☼ Tema claro':'◐ Tema escuro'});
render();
